name: lesgo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_svg: ^2.0.1
  get_storage: ^2.1.1
  intl: ^0.18.0
  http: any
  device_calendar: ^4.3.1
  flutter_native_timezone: ^2.0.0
  location: ^4.4.0
  cached_network_image: any
  flutter_easyloading: ^3.0.5
  google_maps_flutter: ^2.2.6
  pinput: ^2.2.31
  country_picker: ^2.0.20
  permission_handler: ^10.2.0
  pull_to_refresh: ^2.0.0
  flutter_share: ^2.0.0
  connectivity_plus: ^5.0.2
  flutter_bounce: ^1.1.0
  animated_splash_screen: ^1.3.0
  paperfold: ^1.0.3
  google_fonts: any
  image_picker: ^1.0.5
  image_cropper: ^3.0.0
  dotted_border: ^2.0.0+3
  table_calendar: ^3.0.8
  path_provider: ^2.0.15
  file_picker: ^5.2.6
  step_progress_indicator: ^1.0.2
  scrollview_observer: ^1.14.0
  flutter_contacts: ^1.1.7+1
  device_info_plus: ^9.0.1
  html: ^0.15.4
  flutter_html: any
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.2.1
  cloud_firestore: ^4.9.0
  url_launcher: ^6.1.12
  collection: ^1.17.1
  signed_spacing_flex: ^1.1.0
  flutter_slidable: ^3.0.0
  share_plus: ^7.1.0
  photo_view: ^0.14.0
  emoji_picker_flutter: ^1.6.0
  flutter_local_notifications: ^14.0.0+1
  flutter_paypal_native: ^2.0.1
  pay: ^1.1.2
  youtube_player_flutter: ^8.1.2
  firebase_crashlytics: ^3.3.6
  package_info_plus: ^4.1.0
  uni_links: ^0.5.1
  flutter_downloader: ^1.11.3
  network_info_plus: ^4.1.0
  flutter_image_compress: ^2.1.0
  timezone: ^0.9.2
  local_auth: ^2.1.8
  flutter_fgbg: ^0.3.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/svg/
    - assets/images/
    - assets/apple_pay_file/